name: Publish npm package

# 手動起動
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to checkout'
        required: true
        default: 'v0.0.0'

permissions:
  contents: read
  packages: write

jobs:
  pre_checkout_tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Verify Git tag
        run: git describe

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build Docker Image
        run: docker build --file ./Dockerfile.ci --tag openapi-tools:latest .
      - name: Run Docker Container
        run: docker run --name openapi-generator -d -v ./:/workspace openapi-tools

      - name: Verify Docker Container
        run: docker ps

      - name: Run Docker Exec Open API Generator Typescript Axios
        run: docker exec openapi-generator openapi-generator-cli generate -c /workspace/openapitools-axios.json -o /workspace/output/typescript/axios

      - name: Run Docker Exec Open API Generator Typescript Fetcher
        run: docker exec openapi-generator openapi-generator-cli generate -c /workspace/openapitools-fetch-api.json -o /workspace/output/typescript/fetch

      - name: Run Docker Exec Set Directory Permissions
        run: docker exec openapi-generator chmod -R 777 /workspace/output

      - name: Verify After Generation Schema Files
        run: ls -la ./output/typescript

      - name: Create .npmrc File
        run: |
          cd ./output/typescript
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@s-kyono:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Create Package Main Route File
        run: |
          cd ./output/typescript
          cat <<EOF> index.ts
          export * as TypeModelsAxios from './axios';
          export * as TypeModelsFetch from './fetch';
          EOF

      - name: Preare package.json
        run: |
          cd ./output/typescript
          cat <<EOF> package.json
          {
            "name": "@s-kyono/schema-driving-developer-swagger",
            "version": "${{ github.event.inputs.tag }}",
            "description": "swagger schema type files",
            "main": "index.ts",
            "repository": {
              "type": "git",
              "url": "https://github.com/s-kyono/schema-driving-developer-swagger.git"
            },
            "publishConfig": {
              "registry": " https://npm.pkg.github.com"
            },
            "author": "s-kyono <https://github.com/s-kyono>",
            "license": "MIT",
            "devDependencies": {
              "typescript": "5.^6.2",
              "@types/node": "22.^9.0",
              "axios": "1.^7.7"
            }
          }
          EOF

      - name: Publish to Github Packages
        run: |
          cd ./output/typescript
          ls -la ./
          npm config list
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
